### ISSUE TITLE
Problem with import

### ISSUE THREAD

**Issue by tomaszchabinka** [CCLab/degallimaufry#6]
I added reviewed column to monuments table in init_score_db.sql file and now we have problem with import data to database:

[~@localhost scripts]$ node score.js 

> > > parsing file
> > > cleaning up data
> > > pushing data into db

events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: SQLITE_ERROR: table monuments has 5 columns but 4 values were supplied

**Comment by trzewiczek** [comment]
I forgot to put extra '?' into insert statement.
